### ISSUE TITLE
stepSize = 1; tapping on left half of a star doesn't register that star as rating

### ISSUE THREAD

**Issue by iontech** [FlyingPumba/SimpleRatingBar#11]
Ideally regardless of the localtion, the full star should be registered for step size 1.

**Solution Suggestion**:
In `setNewRatingFromTouch(…)`
``` java
private void setNewRatingFromTouch(float x, float y) {
  …

  if (stepSize != Float.MAX_VALUE) {
    float mod = rating % stepSize;

    // --> Old code
    if (mod < stepSize/2) {
      rating = rating - mod;
      rating = Math.max(0, rating);
    } else {
      rating =  rating - mod + stepSize;
      rating = Math.min(numberOfStars, rating);
    }
    // <-- Old code

    // --> New
    rating = rating - mod +stepSize;
    rating = Math.min(numberOfStars, rating);
    // <-- New

  }

  …
}
```

**Comment by FlyingPumba** [comment]
@iontech I like your suggestion, and I just tried it out.
The problem is that once you touch the first star, it's very hard to undo this rating.
The current solution is not great, but it ensures that the user can always choose the rating he/she wants.

What do you think of using `if (mod < stepSize/4)` ? it seems to improve the overall feeling of the rating.

**Comment by iontech** [comment]
The platform provided RatingBar in android doesn't let the user set a zero rating by tapping on the first star. The user has to tap and drag their finger off to the left edge of the rating bar to make it zero stars. So, my best argument is that the platform expects users of the widget to discover this ability and use it as the only means to set zero rating.

**Comment by FlyingPumba** [comment]
@iontech The gesture you mentioned is something I would like to avoid. Although it might be true that it's the standard imposed by the stock RatingBar, we have to also take into account that this widget is implemented by subclassing ProgressBar, where that gesture makes more sense.
I'll use `mod < stepSize/4` in next release of this library in hope that it will improve the usability, and leave this issue open in case we decide to change it later.

**Comment by muddin1** [comment]
I like `mod < stepSize/4`'s behavior better. Preferable.
