### ISSUE TITLE
I hava set the proverty  app:srb_isIndicator="false" in both staic and dynatici way ! but it still didn't work !

### ISSUE THREAD

**Issue by fWX228941** [FlyingPumba/SimpleRatingBar#12]
my request is that I want sinplly the ratingBar to be shown in the solid way not changed by user's finger . that is disable user interaction with ratingBar ! how can I meet the demand ? please do help me !

**Comment by FlyingPumba** [comment]
Hi, I think you misunderstood how to use `isInidicator` property.
- Set it to **true** if you want to **disable** user interaction
- Set it to **false** if you want to **allow** user interaction (this is the default value).
