### ISSUE TITLE
ScrollView parent - Touch vertical drag on SimpleRatingBar widget delegates the drag to ScrollView

### ISSUE THREAD

**Issue by iontech** [FlyingPumba/SimpleRatingBar#13]
I think the widget should only loose its touch state when the user releases or cancels the touch event and not on move.

**Comment by iontech** [comment]
Actually, come to think of it, the delegation of drag to parent view is legit. What, however, should not happen is registering the rating with the widget, i.e. when the touch move is taken over by parent, the widget should not accept the new rating value.

**Comment by FlyingPumba** [comment]
@iontech Thanks for the bug report. I'll look into it in the weekend.

**Comment by FlyingPumba** [comment]
@iontech I think this is really not a problem.
Is not up to the children views whether they can claim or not the touch event. If parent view group decides so, it can intercept all touch events.
Also, this currently works as you described in the second comment in the sample app:

1. User starts a touch event in a SimpleRatingBar.
2. Moving the finger inside the view changes the rating.
3. The moment the user touches outside the rating bar, the drag starts, which means that ScrollView intercepted the touch event for itself.
4. Once this happens the rating bar won't get the touch event again, and so the rating is unchanged during scroll.
