### ISSUE TITLE
Star separation dp scales not working correctly

### ISSUE THREAD

**Issue by nerdymax** [FlyingPumba/SimpleRatingBar#15]
When I set 12dp as the star separation, the distance between the stars are different on different devices.

**Comment by FlyingPumba** [comment]
Thanks for the bug report ! I'll take a look into it.
- What devices have you tried ?
- Are you using latest version (0.1.2) ?

**Comment by nerdymax** [comment]
- I tried two virtual devices of Genymotion. Tablets with different densities - 160dpi and 320dpi.
- Yes I am using v0.1.2.

**Comment by FlyingPumba** [comment]
Fixed in version 0.1.3
