### ISSUE TITLE
cannot select the last haft star, l need scroller to the last, click event doesn't work

### ISSUE THREAD

**Issue by klower** [FlyingPumba/SimpleRatingBar#17]
cannot select the last haft star, l need scroller to the last, click event doesn't work

**Comment by FlyingPumba** [comment]
Hi, thanks for the bug report ! Are you using last version (0.1.3) ?

**Comment by FlyingPumba** [comment]
@klower sorry for the delay. I can't reproduce the first part `cannot select the last haft star`, however click listener will be available in next version.
