### ISSUE TITLE
Rating not accurate

### ISSUE THREAD

**Issue by ericn37** [FlyingPumba/SimpleRatingBar#18]
First of all, your library is the best out there, it really stands out from the competition!

I'm sure I'm missing something very obvious here :)
I'm referring to your demo app.

I have the following in fragment_size_of_stars.xml:
```xml
<com.iarcuschin.simpleratingbar.SimpleRatingBar
            android:id="@+id/ratingBar2"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_margin="8dp"
            app:srb_drawBorderEnabled="true"
            app:srb_borderColor="@color/material_blue500"
            app:srb_fillColor="@color/material_blue300"
            app:srb_pressedBorderColor="@color/material_blueA400"
            app:srb_pressedFillColor="@color/material_blueA200"
            app:srb_starSize="20dp"
            app:srb_rating="4"
            app:srb_stepSize="0.1"
            app:srb_numberOfStars="5"
            app:srb_isIndicator="true"
            />
```
However the result is not 3.3 at all (blue stars; the second rating bar):
![device-2016-11-29-002349](https://cloud.githubusercontent.com/assets/19919208/20676293/38dcad2a-b5ca-11e6-8b4a-6a4dffdaea1f.png)

**Comment by FlyingPumba** [comment]
Thanks for the bug report ! I'll look into it.

**Comment by FlyingPumba** [comment]
@ericn37 sorry for the delay. I think the problem comes from the fact that the rating is calculated without subtracting the separation between stars.. It seems to work just fine for larger stars:

![photo_2016-12-21_18-46-00](https://cloud.githubusercontent.com/assets/1159078/21407145/def644ec-c7ad-11e6-8af2-d025a11452f8.jpg)

**Comment by FlyingPumba** [comment]
@ericn37 hopefully solved. There was a bug in the drawing method which could have caused wrong display of rating due to a wrong float math. Check it out in next version (0.14) and let me know if you find anything suspicious :)

**Comment by mob-rockstar** [comment]
How can I set a float rating like 3.5, 2.3, 4.7?
