### ISSUE TITLE
disable set rating

### ISSUE THREAD

**Issue by Mahdiazadbar** [FlyingPumba/SimpleRatingBar#2]
how can i use simple rating bar for only show rate? not set rating?
thanks for this laibrary

**Comment by Mahdiazadbar** [comment]
app:isIndicator="true"

**Comment by FlyingPumba** [comment]
Hi !
I guess you already answered yourself :)
You can use `app:isIndicator="true"` in XML layout or `myRatingBar.setIsIndicator(true);` in java.
This will disable user interaction with the rating bar.
