### ISSUE TITLE
Using Custom Image for Rating Icon

### ISSUE THREAD

**Issue by arslanraza** [FlyingPumba/SimpleRatingBar#22]
First of all thank you for the awesome library. It is exactly what I need for my current project with the ability to provide custom size.

I was wondering if there is a possibility that we can use a custom star image for the rating icons ?

Thanks

**Comment by FlyingPumba** [comment]
Hi, I'm glad it's being helpful !
Currently that's not possible, because the library doesn't use any images to draw the stars.
