### ISSUE TITLE
How to set the max rating? It seems that max rating is always 5

### ISSUE THREAD

**Issue by timshinlee** [FlyingPumba/SimpleRatingBar#26]
I love this simple but powerful widget. But I don't know how to change the max rating. Thanks A lot!

**Comment by FlyingPumba** [comment]
Hi, @timshinlee. Sorry for the late response.
If you mean the number of stars, you can change it with `app:srb_numberOfStars / setNumberOfStars(int)`

**Comment by timshinlee** [comment]
It doesn't matter. Glad to get your response! I mean the max score to determine how many stars to fill in. It seems the max score is always 5. For example, will I be able to call setRating(5f) in the base of 10, then two and a half stars are filled in instead of all?

**Comment by timshinlee** [comment]
@FlyingPumba It doesn't matter. Glad to get your response! I mean the max score to determine how many stars to fill in. It seems the max score is always 5. For example, will I be able to call setRating(5f) in the base of 10, then two and a half stars are filled in instead of all?

**Comment by FlyingPumba** [comment]
@timshinlee Currently there is no method to change the max rating. It's assumed that the max rating is the number of stars. I might add it in the next version (something like [setMax](https://developer.android.com/reference/android/widget/RatingBar.html#setMax(int)) in Android's official RatingBar).

Until then, you can of course use rule of Three to convert from one range to the other:

```
void setRatingBase10(SimpleRatingBar srb, float ratingBase10) {
    srb.setRating(ratingBase10 / 10f * 5f);
}
float getRatingBase10(SimpleRatingBar srb) {
    return srb.getRating() / 5f * 10f;
}
```

**Comment by timshinlee** [comment]
@FlyingPumba Cool! I will follow your suggestion. Thanks for your kindly help! Hope this won't bother you.
