### ISSUE TITLE
make SimpleRatingBar can't drag

### ISSUE THREAD

**Issue by HRobbie** [FlyingPumba/SimpleRatingBar#28]
I want to let the user see rating but user don't  action.How can I do?

**Comment by shenqinwei** [comment]
I want to let the user see rating but user don't action.How can I do?

**Comment by geriby23** [comment]
How to disable clicks on rating?

**Comment by FlyingPumba** [comment]
Hi, sorry for the late response. All options for this library are listed in the [README](https://github.com/FlyingPumba/SimpleRatingBar/blob/master/README.md).

**Comment by joyceHong0524** [comment]
Just for the random people who faced same problem.

How to use isInidicator property.

Set it to true if you want to disable user interaction
Set it to false if you want to allow user interaction (this is the default value).
