### ISSUE TITLE
app:interaction  Not working 

### ISSUE THREAD

**Issue by raiarainne** [FlyingPumba/SimpleRatingBar#29]
I have tried to make non clickable.
So i have done as following.

<com.iarcuschin.simpleratingbar.SimpleRatingBar
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:id="@+id/rating"
                    app:srb_starSize="25dp"
                    app:srb_numberOfStars="5"
                    app:srb_isIndicator="false"
                    app:srb_rating="3"
                    app:srb_stepSize="0.5"
                    app:srb_borderColor="@color/colorPrimary"
                    app:srb_fillColor="@color/colorPrimary"
                    />

But the rating bar is always clickable though i set " app:srb_isIndicator="false""
How can i solve this issue ?

**Comment by Neha1904** [comment]
@raiarainne You should set  app:srb_isIndicator="true". And that will work.

**Comment by raiarainne** [comment]
Thank you for your answer.
I have been replaced it
But there is no change yet.

**Comment by joyceHong0524** [comment]
Just for the random people who faced same problem.

How to use isInidicator property.

Set it to true if you want to disable user interaction
Set it to false if you want to allow user interaction (this is the default value).
