### ISSUE TITLE
Allowback is enabled

### ISSUE THREAD

**Issue by NaveedALi** [FlyingPumba/SimpleRatingBar#32]
library should no allow backup, I am disabling my app to allow back up, but this library is restricting it. kindly update and let me know

**Comment by rasik1010** [comment]
try bellow , 
add in manifest tag
xmlns:tools="http://schemas.android.com/tools"
add tools:node="replace" in Application tag

**Comment by FlyingPumba** [comment]
Hi, sorry for the late response. I don't know what you mean by "back up", but this is just a library that provides a custom view, nothing more.
