### ISSUE TITLE
The last star can not click when use app:stepSize="1.0". 

### ISSUE THREAD

**Issue by tianshaokai** [FlyingPumba/SimpleRatingBar#6]

**Comment by FlyingPumba** [comment]
Hi, thanks for the bug report !
I'll look into it in these days. Just to be sure, are you using version 0.0.6 ?

**Comment by tianshaokai** [comment]
The master branch, Not the version 0.0.6. I compiled the source code.

**Comment by FlyingPumba** [comment]
Ok, thanks. I'm working on it.

**Comment by zouzoux** [comment]
Yes it's not working please fix!!

**Comment by FlyingPumba** [comment]
Sorry for the long wait, it's fixed in version `0.1.0`.
It's pushed to master branch and available in `jcenter` or `Maven Central`.
