### ISSUE TITLE
Attribute "stepSize" has already been defined

### ISSUE THREAD

**Issue by amorenew** [FlyingPumba/SimpleRatingBar#7]
Hi
i put your library to gradle and i got this error:
Error:(669) Attribute "stepSize" has already been defined
in \app\build\intermediates\res\merged\debug\values\values.xml
i have in it
```
<attr format="integer" name="stepSize"/>
<attr format="float" name="stepSize"/>
```
**Note**:
my gradle:
 compile('com.mikepenz:materialdrawer:5.3.6@aar') {
        transitive = true
    }
    compile('com.mikepenz:fastadapter:1.6.0@aar') {
        transitive = true
    }
    compile(name: 'horizontal_number_picker', ext: 'aar')
    compile(name: 'wheel_picker', ext: 'aar')
    compile 'com.mikepenz:itemanimators:0.2.4@aar'
    compile 'com.mikepenz:fastadapter-extensions:1.6.0@aar'
    compile 'com.android.support:appcompat-v7:23.4.0'
    compile 'com.android.support:support-v4:23.4.0'
    compile 'com.android.support:design:23.4.0'
    compile 'com.android.support:cardview-v7:23.4.0'
    compile 'com.android.support:recyclerview-v7:23.4.0'
    compile 'com.google.code.gson:gson:2.7'
    compile 'com.android.volley:volley:1.0.0'
    compile 'com.github.bumptech.glide:glide:3.7.0'
    compile 'com.android.support.constraint:constraint-layout:1.0.0-alpha5'
    //using custom library for date picker because native date picker select disabled dates
    compile 'com.wdullaer:materialdatetimepicker:2.4.0'
    //for cart count badge in toolbar
    compile 'com.mikepenz:actionitembadge:3.2.6@aar'
    compile 'com.cocosw:bottomsheet:1.+@aar'
    compile 'uk.co.chrisjenx:calligraphy:2.2.0'
    compile 'com.jakewharton:butterknife:8.2.1'
    apt 'com.jakewharton:butterknife-compiler:8.2.1'
    testCompile 'junit:junit:4.12'
    //i use custom rating bar because android native bar isn't fully resizable
    compile 'com.iarcuschin:simpleratingbar:0.0.5'
Thanks

**Comment by FlyingPumba** [comment]
Hi, thanks for the bug report !
I'll change the attribute name in next version so it doesn't collide with other libraries.

**Comment by amorenew** [comment]
thanks

**Comment by amorenew** [comment]
i found the problem in horizontal number picker i forked to add feature to it
i changed stepSize to stepCount in forked library
https://github.com/amorenew/HorizontalNumberPicker/commit/46e635ffcb39db696c788748921a8837627f647d

**Comment by FlyingPumba** [comment]
Amazing ! thanks.
I'll probably change it anyway, to something like `ratingStepSize`, to avoid possible problems to other users.

**Comment by emauro** [comment]
The same problem happens with FillColor

**Comment by amorenew** [comment]
it's better to put prefix like ratingStepSize , ratingFillColor, etc
**really good work**

**Comment by FlyingPumba** [comment]
I decided a different approach.
I realized that libraries like [FAB](https://github.com/makovkastar/FloatingActionButton) add a prefix `fab_` to the attributes, so I'm adding `srb_`.
Already pushed to `jcenter` and `Maven Central` as version 0.0.7, try it out ! :)
